<?php

namespace Lljm\HealthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightRepository extends EntityRepository
{

  public function getWeights($datefrom, $dateto, $user)
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.weightValue,
      b.firstname,
      a.dateRead
      FROM LljmHealthBundle:Weight a
      JOIN LljmUserBundle:User b WITH a.user = b.id
      WHERE a.dateRead BETWEEN '$datefrom' and '$dateto'
      and b.id = '$user'
      ORDER BY a.dateRead asc
      ")
    ;

    return $query->getResult();
  }

  public function getUsers()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.firstname
      FROM LljmUserBundle:User a
      WHERE a.username <> 'admin'
      GROUP BY a.firstname
      ORDER BY a.firstname
      ")
    ;

    return $query->getResult();
  }

}
