lljm_geolocation:
    resource: "@LljmGeolocationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

geolocation_remotelog:
    path:     /geolocation_remotelog/{userid},{latitude},{longitude},{altitude},{speed},{direction},{battery},{logdate}
    defaults: { _controller: LljmGeolocationBundle:Remotelog:logrecord }

lljm_admin:
    resource: "@LljmAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

lljm_health:
    resource: "@LljmHealthBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

lljm_home:
    resource: "@LljmHomeBundle/Resources/config/routing.yml"
    prefix: /{_locale}

lljm_homepage:
    path:   /
    defaults:  { _controller: "LljmHomeBundle:Default:index" }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile