<?php

namespace Lljm\TasksBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

  public function getTaskrecords()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.taskdesc,
      a.dateStart,
      a.dateEnd,
      b.username,
      a.completed
      FROM LljmTasksBundle:Task a
      JOIN LljmUserBundle:User b WITH a.user = b.id
      ORDER BY a.completed, a.dateStart
      ")
    ;

    return $query->getResult();

  }

  public function getUsers()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.firstname
      FROM LljmUserBundle:User a
      WHERE a.username <> 'admin'
      GROUP BY a.firstname
      ORDER BY a.firstname
      ")
    ;

    return $query->getResult();
  }

}
