<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HeatingLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatingLogRepository extends EntityRepository
{

  public function GetHeatingLog()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.textlog,
      a.boilerstatus
      FROM LljmHomeBundle:HeatingLog a
      ");
    return $query->getResult();

  }

}
