<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HeatingmodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatingmodeRepository extends EntityRepository
{
}
