<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends EntityRepository
{

  public function GetHouse()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.address1,
      a.address2,
      a.postcode,
      a.city,
      a.country
      FROM LljmHomeBundle:House a
      ORDER BY a.address1
      ");
    return $query->getResult();

  }

}
