<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeterRepository extends EntityRepository
{
  public function Getmeter()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.metername,
      b.resourcename,
      c.unitname
      FROM LljmHomeBundle:Meter a
      LEFT JOIN LljmHomeBundle:Resource b WITH a.resource = b.id
      LEFT JOIN LljmHomeBundle:Unit c WITH a.unit = c.id
      ORDER BY a.id
      ");
    return $query->getResult();
  }

  public function getElecmeters()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.metername
      FROM LljmHomeBundle:Meter a
      LEFT JOIN LljmHomeBundle:Resource b WITH a.resource = b.id
      WHERE b.id = 2
      ")
    ;

    return $query->getResult();
  }

  public function getWatermeters()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.metername
      FROM LljmHomeBundle:Meter a
      LEFT JOIN LljmHomeBundle:Resource b WITH a.resource = b.id
      WHERE b.id = 1
      ")
    ;

    return $query->getResult();
  }

  public function getGasmeters()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.metername
      FROM LljmHomeBundle:Meter a
      LEFT JOIN LljmHomeBundle:Resource b WITH a.resource = b.id
      WHERE b.id = 3
      ")
    ;

    return $query->getResult();
  }

}