<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{

  public function Getunit()
  {
	$em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.resourcename
      FROM LljmHomeBundle:Resource a
      ORDER BY a.resourcename
      ");
    return $query->getResult();

  }

}
