<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubzoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubzoneRepository extends EntityRepository
{

  public function Getsubzone()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.subzonename
      FROM LljmHomeBundle:Subzone a
      ORDER BY a.subzonename
      ");
    return $query->getResult();

  }
}
