<?php

namespace Lljm\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository
{

  public function Getzone()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.zonename,
      a.heatingenabled,
      a.currenttemp,
      a.heatingstatus,
      a.ventilationstatus
      FROM LljmHomeBundle:Zone a
      ORDER BY a.zonename
      ");
    return $query->getResult();

  }

  public function GetHeatingzone()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.zonename,
      a.tempeco,
      a.tempcomfort,
      a.currenttemp,
      b.modedesc,
      a.heatingstatus
      FROM LljmHomeBundle:Zone a
      LEFT JOIN LljmHomeBundle:Heatingmode b WITH b.id=a.heatingmode
      WHERE a.heatingenabled = 1
      ORDER BY a.zonename
      ");
    return $query->getResult();

  }

  public function GetVentilationzone()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id,
      a.zonename,
      a.ventilationschedule,
      a.ventilationstatus
      FROM LljmHomeBundle:Zone a
      WHERE a.ventilationenabled = 1
      ORDER BY a.zonename
      ");
    return $query->getResult();

  }

  public function GetBoilerzone()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.id
      FROM LljmHomeBundle:Node a
      WHERE a.nodesubzone = 2
      ");
    return $query->getResult();

  }

  public function getOutsideTemp()
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      SELECT
      a.currenttemp
      FROM LljmHomeBundle:Zone a
      WHERE a.id = 11
      ");
    return $query->getResult();

  }

  public function setHeatingmodeallzones($heatingmode)
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      UPDATE LljmHomeBundle:Zone a
      set a.heatingmode = '.$heatingmode.'
      ");
    return $query->getResult();

  }

  public function setHeatingmodeonezone($id, $heatingmode)
  {

    $em = $this->getEntityManager();
    $query = $em->createQuery("
      UPDATE LljmHomeBundle:Zone a
      set a.heatingmode = '.$heatingmode.'
      where a.id = '$id'
      ");

    return $query->getResult();

  }
}
